"""add_performance_indexes

Revision ID: 8cd3afe2734e
Revises: fda9e1803e87
Create Date: 2026-09-18 12:19:43.974615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd3afe2734e'
down_revision: Union[str, None] = 'fda9e1803e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    with op.batch_alter_table('department_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_transactions_status'), ['status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    with op.batch_alter_table('department_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_department_transactions_created_at'))

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_created_at'))

    # ### end Alembic commands ###
