"""0001_initial_schema

Revision ID: fda9e1803e87
Revises: 
Create Date: 2026-09-18 10:37:37.392551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda9e1803e87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_mr', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_mr', sa.Text(), nullable=True),
    sa.Column('participating_departments', sa.JSON(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.Column('registration_status', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_mobile'), ['mobile'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_number', sa.String(length=64), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_department', sa.String(length=50), nullable=False),
    sa.Column('citizen_data', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_application_number'), ['application_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_applications_citizen_id'), ['citizen_id'], unique=False)

    op.create_table('assistant_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('resident_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('marital_status', sa.String(length=32), nullable=True),
    sa.Column('community_caste', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('taluk', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=128), nullable=True),
    sa.Column('aadhaar_last_four', sa.String(length=4), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('passport_status', sa.String(length=50), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('telephone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('educational_qualification', sa.String(length=128), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('account_number_masked', sa.String(length=64), nullable=True),
    sa.Column('ifsc', sa.String(length=32), nullable=True),
    sa.Column('passport_document_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resident_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resident_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('assistant_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tamper_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tamper_hash'), ['tamper_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consent_number', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('data_categories', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('consent_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_consent_number'), ['consent_number'], unique=True)

    op.create_table('department_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('source_department', sa.String(length=50), nullable=True),
    sa.Column('destination_department', sa.String(length=50), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_transactions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_transactions_department_id'), ['department_id'], unique=False)

    op.create_table('grievances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievances_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('sla_escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('target_department', sa.String(length=50), nullable=False),
    sa.Column('sla_days_allotted', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('escalation_level', sa.String(length=50), nullable=False),
    sa.Column('escalated_to', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expedited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_escalations_application_id'), ['application_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('verifier_id', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_application_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('sla_escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_escalations_application_id'))

    op.drop_table('sla_escalations')
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievances_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_grievances_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_grievances_application_id'))

    op.drop_table('grievances')
    with op.batch_alter_table('department_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_transactions_department_id'))
        batch_op.drop_index(batch_op.f('ix_department_transactions_application_id'))

    op.drop_table('department_transactions')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_consent_number'))
        batch_op.drop_index(batch_op.f('ix_consents_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_consents_application_id'))

    op.drop_table('consents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tamper_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_application_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_messages_conversation_id'))

    op.drop_table('assistant_messages')
    with op.batch_alter_table('resident_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resident_profiles_user_id'))

    op.drop_table('resident_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))

    op.drop_table('assistant_conversations')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_applications_application_number'))

    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mobile'))
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
